version: "3.2"

services:
  updater:
    image: crazymax/csgo-server-launcher:latest
    container_name: csgo-updater
    command:
      - "csgo-server-launcher"
      - "update"
    env_file:
      - "./csgo-server-launcher.env"
    volumes:
      - "./csgo:/var/steamcmd/games/csgo"
      - "./steam:/home/steam/Steam"
    tty: true
    restart: on-failure
